In [1]:
import numpy

matrix = numpy.array(
    [
        [-0.821323, -0.399593, 0.407129, 15.330742],
        [-0.176946, 0.856931, 0.484107, -11.724613],
        [-0.542327, 0.325568, -0.774523, 20.950329],
        [0.000000, 0.000000, 0.000000, 1.000000]
    ]
)

inv_matrix = numpy.linalg.pinv(matrix)

print("Original matrix:")
print(matrix)
print("Inverted matrix:")
print(inv_matrix)

Original matrix:
[[ -0.821323  -0.399593   0.407129  15.330742]
 [ -0.176946   0.856931   0.484107 -11.724613]
 [ -0.542327   0.325568  -0.774523  20.950329]
 [  0.         0.         0.         1.      ]]
Inverted matrix:
[[-8.21322826e-01 -1.76945862e-01 -5.42327434e-01  2.18788048e+01]
 [-3.99593194e-01  8.56930926e-01  3.25568488e-01  9.35247670e+00]
 [ 4.07129016e-01  4.84106742e-01 -7.74523814e-01  1.56609030e+01]
 [-3.30826916e-17 -4.52533788e-17 -8.60144192e-17  1.00000000e+00]]
